---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# nice99setup

The goal of nice99setup is to provide a template for an R package project to start off. You will need to finish the rest.

``` r
remotes::install_github('Throwback8491/nice99setup')
```

# Further setup instructions

1.  use_X_license

2.  use_author

3.  edit \_sinewconfig.yml author

4.  find and replace all instances of "nice99setup" and replace them with the title of the package you actually want to make

5.  run the commented out renv::install command in R/addin_libs.R then delete it

6.  exit Rstudio

7.  rename the Rproj file to the same thing as step 4

8.  delete the git repo

9.  reopen rstudio

10. temporarily move "R/ZZZ_utils.R" to somewhere outside the git repo

11. use_git()

12. add ZZZ_utils.R back in, and add it to the exclude gitignore file in the new repo

This next one is only once per computer

add the following snippet (but better formatted). my_sinew_force will be a living list that keeps growing as I discover annoying sinew namespacing defaults

snippet nss	usethis::use_r("\${1}")	sinew::pretty_namespace("R/\${1}.R", force = my_sinew_force, overwrite = TRUE)	file.remove("R/\${1}.R")
